/**
 * 默认只有2级菜单
 */
const leftmenu = [
    {
      name:'大棚温室',
      icon:'icon-dapengwenshi',
      path:'/shalter',
      children:[{
        name:'大棚温室管理',
        icon:'',
        path:'/shalter/list',
      },{
        name:'草莓大棚',
        icon:'',
        path:'/shalter/detail',
      }]
    },
    {
        name:'大田',
        icon:'icon-datian',
        path:'/field',
        children:[{
          name:'大田设备管理',
          icon:'',
          path:'/field/tree',
        },{
          name:'蓝莓大田',
          icon:'',
          path:'/field/detail',
        }]
    },
    {
      name:'视频监控',
      icon:'icon-shipinjiankong',
      path:'#1',
    },
    {
      name:'灌溉系统',
      icon:'icon-bengzhan',
      path:'/watering/map',
    },
    {
      name:'农事管理',
      icon:'icon-nongshiguanli',
      path:'#2',
    },
    {
      name:'事件报警',
      icon:'icon-shijianbaojing',
      path:'#3',
    },
    {
      name:'人员管理',
      icon:'icon-renyuanguanli',
      path:'/user',
    },
  ]

  export  default leftmenu
